minimumReleaseAge: 0
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

catalog:
  "@types/node": ^26.0.0
  "@zinkawaii/eslint-config": ^0.4.5
  "@zinkawaii/tsconfig": ^0.1.0
  bumpp: ^11.1.0
  citty: ^0.2.2
  consola: ^3.4.2
  eslint: ^10.5.0
  tinyexec: ^1.2.4
  tsdown: ^0.22.3
